# Generated by Django 5.2.8 on 2025-11-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created_at'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
    ]
