# Generated by Django 5.2.8 on 2025-12-16 23:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
